apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-with-hpa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: hpa-test
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  
  # Ignorer les replicas (géré par HPA)
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas