apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: default
spec:
  encryptedData:
    api-key: AgAEWrkz7rv3kfAeVCzM9P5lkCbvRm1iyZoNxDuvHDoQ1CbD/F7MyIdlktYnkAOgWY/PoEWdcwnCgjR34bPEBoW5HzcYJhJXqQpr0XrdZL8ptrzVQK0Guido5nwDXIymYSZK/vXqyobDQ0iLyVVqY+0Qe4s1hmidVFzbBLI0S2tBTwmJgduftomb6eZH0hWxvqH8EP5LZr/8+2RGy4gT9fAmgpUPyT6BKs9h2FIxK05M3loC7IvE0CIR+25KlQU5wOzfyOu8eg8lHm8MhA78MdSSom/wNEODkQAC/RiQzJXuZTBmh2blfD6N3c5gwFpOYD8yQm0lBKdCvD9GaU0ec/qYJ8VTO/5hakJ+DX08CbvZfjAUkcZRnvzOfu8e3EikqJEAFUdA1ZZ1/xg9rNlrQXN4AsIwEzqsXOYQeAHG5IJtyNqixNu+zXPqWAL7EZFx66KyumMic4TlfrB/E25zx3h4sueML5sp20T77V2okka/n45NabLSfT7nR0e0iMSCo6/OJQqbuKepmlulxZT6gHwHFEBSjL+OjyK4cQosF7wT7WlMC8ihr12XHIPfhYS7V3vY8tA+4wmfPXuL+3wTJ4JHj/V6FptJbiCCYAI5Ur2tiEC/vVbLhCexrynhuLsEzWGJxFNuUJETVwxVl3UAuvNe68dKoYhh5MlHhGPlKoYXcr/C4GJTC2a2Lh97fRFlulhs9bIwWKDocr5rvA==
    db-password: AgCM2hSUroBckTx3EhkCVqp1eICcxK+g0earRGiCKJrVXRrId6Wf02pshVhPCViSUrgYn23Sz5E+zqA38jew+rFOh4P8MBNTMuu3vAS72y/qFfdIXmeb82dO9Met6x/i8MqzHTOvfcu5sso6BmUmYCe8nVK1daB4s9yNkek7PM/tNjF8e590785w6rf8Nu+2tGhQYB8oH9SJ+EL22Na+ZU3czewuqPPEzJfQD0wxKZYo86Tpm41e0wCjqMa/6zko33LG0ND+mF88yBzjNuhRZwFlfH8Qfrmgadd6A18EOWmq+uL5BGygbIOgpQ+UxYNy18IBEiETwmnosNcc+6m3eC7r32ea1cJlJdUk2hxvproLvX9yUnRmeZrkSi6NJLKLEsS3CesPW0RDLDmHG1aJRmiEc0aQpKmccDjBGeONiH91fUUorys8IkKbXCrYnHIiOxyyFKAl62HRCXzwq3UnwhJvNGSz3FH1cAw1I1Thl8hYSz7o2/XLDR1sAyVMhiueHgy6z2bkxPDQ+vKnDx8qI7UlzpQgtAjhER1nsy2eZ7XYJ3WqJ1G82sT5iyKVHP8fJldOInjDdKgpB9W0nvTqjv849APAj3LKlFTTYOCJZQdyx4cey5lYA4ooERisqfvkvBONzqpDwYkgDiB5jsUVbxJ4JDRHm1Dab3m07blOyk8Z4/zQ4xyHY9R1Vtgf+UhIBjOHdHGJbfGt8waTybVZvw==
  template:
    metadata:
      creationTimestamp: null
      name: app-secrets
      namespace: default
---
